### ISSUE TITLE
the name clashed with the "official" ROS leg_detector, please rename

### ISSUE THREAD

**Issue by marc-hanheide** [marcobecerrap/edge_leg_detector#3]

**Comment by marcobecerrap** [comment]
Hi @marc-hanheide 
@ferdianjovan and I have changed the name of the package, the CMakeLists.txt and package.xml and the readme file. Could you please check if the changes look good.
Thanks

**Comment by marc-hanheide** [comment]
I cloned and tested briefly. Looks good and installs correctly. Well done, I'd say!

**Comment by marc-hanheide** [comment]
If you don't mind, I suggest to fork in into strands-project and then release it into a Debian package?

**Comment by marc-hanheide** [comment]
I configured our build farm to release Debian packages. It succeeded. Good job! From now on people can simply do `apt-get install ros-indigo-edge-leg-detector` if they have the STRANDS repo configured (https://github.com/strands-project-releases/strands-releases/wiki#using-the-strands-repository)
